---

- name: (schema) Import schemas
  shell: 'ldapadd {{ ldap_connection }} -f {{ workspace }}/{{ item.file }}'
  environment:
    bind_password: '{{ bind_password }}'
  with_items:
    - { file: schema.ldif }
    - { file: pwm-schema.ldif }
